language: python
python:
  - "2.7"
env:
  - DJANGO=1.3.7
  - DJANGO=1.4.5
  - DJANGO=1.5.1
# command to install dependencies
install:
  - pip install -q Django==$DJANGO --use-mirrors
#  - pip install pep8 --use-mirrors
  - pip install -r requirements.txt --use-mirrors
before_script:
  - "pep8 --exclude=migrations --ignore=E501,E225 src"
# command to run tests
script: python manage.py test
